# Generated by Django 5.2.5 on 2025-08-08 19:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledemail',
            options={'ordering': ['-scheduled_at']},
        ),
        migrations.AddField(
            model_name='scheduledemail',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='scheduledemail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
