# Generated by Django 5.2.5 on 2025-08-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_alter_scheduledemail_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledemail',
            options={'ordering': ['-scheduled_at'], 'verbose_name': 'Scheduled Email', 'verbose_name_plural': 'Scheduled Emails'},
        ),
        migrations.AlterField(
            model_name='scheduledemail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
