# Generated by Django 5.2.5 on 2025-08-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_scheduledemail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledemail',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
