# Generated by Django 5.2.5 on 2025-08-07 21:14

import users.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=users.storage.ProfilePictureStorage(), upload_to=''),
        ),
    ]
